/**
 * @file ternary_gates_catalog.h
 * @brief Catalog of Important Ternary Logic Functions
 * @author TEROS Development Team
 * @date 2025
 */

#ifndef TERNARY_GATES_CATALOG_H
#define TERNARY_GATES_CATALOG_H

#include <stdint.h>

// =============================================================================
// WELL-KNOWN DYADIC FUNCTIONS
// =============================================================================

// These IDs were auto-generated by ternary_gates_generator.py

// Kleene AND: min(a, b)
// Truth table: (-1,-1):-1, (-1,0):-1, (-1,+1):-1, (0,-1):-1, (0,0):0, (0,+1):0, (+1,-1):-1, (+1,0):0, (+1,+1):+1
#define T3_GATE_CATALOG_KLEENE_AND 15633

// Kleene OR: max(a, b)
// Truth table: (-1,-1):-1, (-1,0):0, (-1,+1):+1, (0,-1):0, (0,0):0, (0,+1):+1, (+1,-1):+1, (+1,0):+1, (+1,+1):+1
#define T3_GATE_CATALOG_KLEENE_OR 19569

// Consensus: median(a, b, 0)
// Truth table: (-1,-1):-1, (-1,0):-1, (-1,+1):0, (0,-1):-1, (0,0):0, (0,+1):0, (+1,-1):0, (+1,0):0, (+1,+1):+1
#define T3_GATE_CATALOG_CONSENSUS 16371

// Minority: opposite of consensus
// Truth table: (-1,-1):+1, (-1,0):+1, (-1,+1):0, (0,-1):+1, (0,0):0, (0,+1):0, (+1,-1):0, (+1,0):0, (+1,+1):-1
#define T3_GATE_CATALOG_MINORITY 3311

// PLUS: Ternary addition (a + b) mod 3
// Truth table: (-1,-1):+1, (-1,0):-1, (-1,+1):0, (0,-1):-1, (0,0):0, (0,+1):+1, (+1,-1):0, (+1,0):+1, (+1,+1):-1
#define T3_GATE_CATALOG_PLUS 5681

// TIMES: Ternary multiplication (a * b)
// Truth table: (-1,-1):+1, (-1,0):0, (-1,+1):-1, (0,-1):0, (0,0):0, (0,+1):0, (+1,-1):-1, (+1,0):0, (+1,+1):+1
#define T3_GATE_CATALOG_TIMES 15665

// =============================================================================
// MONADIC FUNCTIONS (well-known)
// =============================================================================

// Identity: f(x) = x
#define T3_GATE_MONADIC_IDENTITY 13

// Negation/NOT: f(x) = -x
// Maps: -1→+1, 0→0, +1→-1
#define T3_GATE_MONADIC_NOT 11

// Constant -1: f(x) = -1
#define T3_GATE_MONADIC_CONST_NEG 0

// Constant 0: f(x) = 0
#define T3_GATE_MONADIC_CONST_ZERO 13

// Constant +1: f(x) = +1
#define T3_GATE_MONADIC_CONST_POS 26

// Increment (mod 3): f(x) = x + 1 mod 3
// Maps: -1→0, 0→+1, +1→-1
#define T3_GATE_MONADIC_INCREMENT 25

// Decrement (mod 3): f(x) = x - 1 mod 3
// Maps: -1→+1, 0→-1, +1→0
#define T3_GATE_MONADIC_DECREMENT 19

// Threshold positive: f(x) = (x == +1) ? +1 : -1
#define T3_GATE_MONADIC_THRESHOLD_POS 8

// Threshold negative: f(x) = (x == -1) ? +1 : -1
#define T3_GATE_MONADIC_THRESHOLD_NEG 22

// =============================================================================
// FUNCTION CATEGORIES
// =============================================================================

// AND-like functions: general conjunctive functions
// Examples: KLEENE_AND, CONSENSUS

// OR-like functions: general disjunctive functions
// Examples: KLEENE_OR, MINORITY

// XOR-like functions: general exclusive functions
// Examples: PLUS, TIMES

// Arithmetic functions: operations from arithmetic
// Examples: PLUS, TIMES

// Comparison functions: relations between values
// Examples: various comparison functions

// =============================================================================
// FUNCTIONAL COMPLETENESS
// =============================================================================

// The following sets are known to be functionally complete:

// Set 1: {KLEENE_AND, KLEENE_OR, NOT}
// This is the ternary equivalent of {AND, OR, NOT} in binary

// Set 2: {CONSENSUS, NOT}
// Consensus is a universal gate for ternary logic

// Set 3: {PLUS, TIMES, NOT}
// Arithmetic-based universal set

// =============================================================================
// USAGE EXAMPLES
// =============================================================================

/*
// Evaluate Kleene AND: min(a, b)
trit_t result = ternary_gate_eval(T3_GATE_CATALOG_KLEENE_AND, a, b);

// Evaluate ternary addition
trit_t sum = ternary_gate_eval(T3_GATE_CATALOG_PLUS, a, b);

// Apply NOT
trit_t not_a = ternary_gate_monadic(T3_GATE_MONADIC_NOT, a);
*/

#endif // TERNARY_GATES_CATALOG_H

