version: '3.8'

services:
  lambda3-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "from lambda3.parser.parser import parse; parse('\\x.x')"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - lambda3-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - lambda3-network

networks:
  lambda3-network:
    driver: bridge

volumes:
  redis-data:

