name: TEROS CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run Python tests
      run: |
        pytest tests/ -v --cov=src/lib/teros --cov=Lambda3_Project/lambda3
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      
  build-c:
    name: Build C Kernel
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nasm qemu-system-x86
        
    - name: Build kernel
      run: |
        make clean
        make all
        
    - name: Test in QEMU
      run: |
        timeout 10 qemu-system-x86_64 -kernel bin/teros.bin -serial stdio || true
        
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t teros:latest .
        
    - name: Test Docker containers
      run: |
        docker-compose up -d
        docker-compose ps
        
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install linting tools
      run: |
        pip install flake8 black mypy pylint
        
    - name: Lint Python code
      run: |
        flake8 src/lib/teros Lambda3_Project/lambda3
        black --check src/lib/teros Lambda3_Project/lambda3
        
    - name: Lint C code
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --suppress=missingIncludeSystem src/kernel/ src/boot/

